// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cfntqnvyhhuysdoxaozh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmbnRxbnZ5aGh1eXNkb3hhb3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0NTg0OTAsImV4cCI6MjA2MDAzNDQ5MH0.Z6nZmIhqGm7j662ktjszIgwrq9IdBIe5Ndev58t5YpI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);